### PR TITLE
Added Option to use either ghci or runghc

### PR DESCRIPTION
**Pull request by afonsofrancof**
Some people might prefer to use compiled code instead of interpreted,  so it runs instantly when they click the "Run" button.
This requires a main function, and a different runner, so I also updated the requirements in README.md and added a toggle in the settings.

### CODE REVIEW

**Comment by afonsofrancof** [comment]
> I didn't use Haskell for a while, what is the benefit of adding a switch button instead of just changing the value of the existing path variable?


At first I considered that , but I thought it would look weird to have one field for 2 different compilers.
But if you think it looks better , I can just change the wording on the settings.

**Comment by twibiral** [comment]
I think it's good how you implemented it. But it's not possible to easily merge it with develop, could you update your branch based on develop?

**Comment by afonsofrancof** [comment]
Done :)

**Comment by twibiral** [comment]
Thank you!

**Pull request merged**
