### PR TITLE
Interactive input for code blocks

### PR DESCRIPTION
**Pull request by chlohal**
Allow users to interactively submit things to `stdin` with an input element. I didn't put much effort into the styling of the input element, but please feel free to let me know if that is a thing that I can help with!

- May complete Future Work item # 2 ("Notebook Mode similar to Jupyter"); I'm unsure if that's what you meant or not, though

### CODE REVIEW

**Comment by twibiral** [comment]
Thank you for this contribution! The feature works great!

I think it is styled enough and looks good. "Notebook Mode similar to Jupyter" means that the variables of a code block are stored independent of the block and are accessible from the other blocks.

Could you add some documentation for the methods before merging?

**Comment by chlohal** [comment]
Sure! I've added some JSDoc comments; please let me know if inline comments would help as well :)

**Comment by twibiral** [comment]
Thank you very much! Your work is great!

**Comment by twibiral** [comment]
Released in [0.17.0](https://github.com/twibiral/obsidian-execute-code/releases/tag/0.17.0)

**Comment by chlohal** [comment]
Wonderful! Thank _you!_

**Pull request merged**
