### PR TITLE
Fix input box show on print

### PR DESCRIPTION
**Pull request by qiaogaojian**
I found that the input box always show and hide when I printing log with python. It is annoying. 

makeOutputVisible() method is called when write text to output element, input box always show on this method is called, after 
child process's work is done, closeInput() method is called. this is why input box show and hide.

To fix this issue, I add closeInput() at the start of makeOutputVisible() method, and increase input box show delay time.  before input box show, next makeOutputVisible() call, then closeInput() call, so the pre line input box will never show. 

Before:
Obsidian_61W98tdHQF

After:
Obsidian_qjKIoilkvG

### CODE REVIEW

**Comment by chlohal** [comment]
I like the `closeInput()` after every print. That definitely helps with the issue. However, I'm unsure about increasing the timeout: in cases such as below, this can be annoying because it requires the user to wait for each input:

input-delay

**Comment by qiaogaojian** [comment]
with default delay time which is 400ms, the input box still show like below.

then I tested with 800ms, still. at last, I found increase to 1000ms works.

print log is much more common used than get input, so I think increase input delay from 400ms to 1000ms is acceptable.

**Comment by qiaogaojian** [comment]
I found that it is this line in my test code is the reason of why increase to 1000ms works.
image
It's my fault, I'll revert to orginal delay.

**Comment by qiaogaojian** [comment]
closed, I make another request with no delay time hacking.

**Pull request closed without merging**
