### PR TITLE
Feature/support ts cs lua

### PR DESCRIPTION
**Pull request by qiaogaojian**
support typescript c# lua

### CODE REVIEW

**Comment by qiaogaojian** [comment]
I'm tring to add support with more language such as solidity.

**Comment by qiaogaojian** [comment]
> When you merge this request, I'll close another.

closed

**Comment by twibiral** [comment]
Looks good! I am unsure about your use of `runCodeInShell(...)` instead of `runCode(...)`. Do the languages you implemented need the shell's support to be executed? Otherwise, it could make sense to skip the shell environment and execute it without shell.

Either way, I think your changes are ready to be merged and released when I am free.

**Comment by twibiral** [comment]
I tested it and it looks like it is necessary to use a shell environment so we can just keep it as it is.

**Pull request merged**
