### PR TITLE
Replace JSCPP with Cling for C++

### PR DESCRIPTION
**Pull request by milan338**
JSCPP is nice to have in that it doesn't require any dependencies from the user, but the tradeoff is a much larger plugin size and a very limited set of features. [Cling](https://github.com/root-project/cling) provides a much greater C++ experience, and removes the need for a bundled interpreter, taking the plugin down from around 1.4mb to only around 430kb. This PR removes JSCPP from the plugin and adds support for Cling, along with the ability to inject code at the beginning of each C++ code block.

### CODE REVIEW

**Comment by twibiral** [comment]
Does Cling work on Windows too?

**Comment by twibiral** [comment]
Before merging, please change
```
let codeContent = codeBlockContent;
if (ext === "cpp")
	codeContent = codeContent.replace(/main\(\)/g, `temp_${fileId}()`);
```
to the simpler
```js
codeBlockContent = ext === "cpp" ?  codeBlockContent.replace(/main\(\)/g, `temp_${fileId}()`);

// OR

if (ext === "cpp")
	codeBlockContent = codeBlockContent.replace(/main\(\)/g, `temp_${fileId}()`);
```
the extra variable isn't really needed (as replace returns a new string)

**Comment by twibiral** [comment]
Thank you for your contribution! I will release it soon with the next release.

As a sidenote: I like how you implemented the option to execute code before the code block. This was also requested in #22

**Comment by renrenxiao** [comment]
> 



> Does Cling work on Windows too?
> 
> Edit: Yes it does.

how to work this plugin with cling on Windows

**Comment by chlohal** [comment]
Install cling, make sure it's added to your `PATH` environment variable, & everything should work! :)

**Pull request merged**
