### PR TITLE
Added Groovy Support

### PR DESCRIPTION
**Pull request by cdrchops**
I'm not sure if this is an elegant solution.  It does work; I use it locally.  There may be a better way.  I'll leave that decision up to you all.

### CODE REVIEW

**Comment by twibiral** [comment]
Thank you for the contribution!

There are some things to change before I can merge the pull request:
- [main.ts line 31] Remove the hard coded default option in the groovy path. This way it only works on your local machine. Change it to "groovy" and it will work on every OS (if groovy added to the path variable)
- [main.ts 122] Remove the outcommented `/* || language.contains("language-javascript")*/`.
- [main.ts line 198-212]
```typescript
.then(() => {
        console.log(`Execute ${this.settings.nodePath} ${tempFileName}`);
        const args = cmdArgs ? cmdArgs.split(" ") : [];
        
        args.push(tempFileName);
        
        if (ext === "groovy") {
	        exec('groovy '+tempFileName, (error :any, stdout:string, stderr:string) => {
		        this.handleExecOutput(outputter, button, tempFileName, stdout, stderr);
	        });
        } else {
	        var child = child_process.spawn(cmd, args);
	        this.handleChildOutput(child, outputter, button, tempFileName);
        }
})
```
Revert that code snippet to the way it previously was and try if it works. There is no need to change this because it uses the path to the groovy installation that is given via the function parameter
- [main.ts 299] Remove the function `handleExecOutput` as it is obsolete after following the previous remark.
- [SettingsTab.ts] Add the options you created as html elements. Otherwise the options can't be changed by users. You can copy the JavaScript elements and change the names and variables. Also: Does groovy has the option to use different file extensions? There is no need to add an option to the settings tab if all groovy files have the same file extension. (I can impement this if you don't now what to do, just tell me)

Again, thank you for your Contribution, I really appreciate it.

**Comment by cdrchops** [comment]
Thank you for your notes.  I appreciate the guidance.  I went ahead and removed the exec function and call I created.  Locally, for me, running spawn does not work that's why I added the new function.  If you have any insight on this, I'd appreciate it.

**Comment by twibiral** [comment]
I released your changes (and some other). If it still doesn't work we can look for a fix.

**Comment by cdrchops** [comment]
Thank you.  Locally, it does not work for me.
I'm using Node v18.4.0 on Windows 10

**Comment by twibiral** [comment]
> Thank you.  Locally, it does not work for me.
> I'm using Node v18.4.0 on Windows 10

Okay, if you know how to fix it you can create a new pull request and I will merge it

**Comment by twibiral** [comment]
But please create the pull request on the develop branch instead of master

**Pull request merged**
