### PR TITLE
Fix python notebook mode freezing after showing matplotlib plot

### PR DESCRIPTION
**Pull request by milan338**
Fixes the bug discussed in #103 where calling `plt.show()` for a matplotlib plot in python notebook mode would freeze the runtime and prevent running code again while leaving a runaway python instance in the background. The fix is to just change the matplotlib backend to the non-interactive 'agg' option if matplotlib is used in the code block.

### CODE REVIEW

**Comment by chlohal** [comment]
Amazing; thanks so much!! 

I have one question: why call `matplotlib.use()` in every code block? It seems to make more intuitive sense to me to call it once in the initial setup code. Although it couldn't be conditional on *use* of matplotlib, it could be based on the `pythonEmbedPlots` setting.

**Comment by milan338** [comment]
I've moved the matplotlib import to the initial code setup, however I've left the `matplotlib.use()` calls up to each code block so that it's possible to toggle the 'embed plots' option, I hope this is an ok way to do it. Looking into this issue further though, we can't use a non-interactive backend when embed plots is off, so the original issue persists when not embedding plots. I've tracked it down to `plt.plot()` spawning the backend process, but I couldn't find a way to fix this yet.

**Comment by chlohal** [comment]
That makes sense. Thank you!

**Comment by chlohal** [comment]
I looked through `plt.plot()`'s source code, and I'm not sure if it *does* spawn that background process. It might be different on windows/mac/linux, but on Windows 10, the only process I see is the Python process that hosts the REPL. I'm quite not sure that that's what you're talking about, but I wanted to let you know :) sorry

**Comment by milan338** [comment]
I just observed on my mac when for example setting `matplotlib.use('tkagg')`, as soon as I run `plt.plot()` in my terminal, the tk feather icon pops up in my dock, and it stays there until the REPL is closed, it looks like it's opening a window in the background, not sure what it's doing exactly though, haven't looked into the source code yet.

**Comment by twibiral** [comment]
Looks good, thank you!

**Pull request merged**
