### PR TITLE
Add code block arguments

### PR DESCRIPTION
**Pull request by milan338**
As discussed in #62, the `pre-` and `post-` syntax is a bit awkward and not very future-proof, so this PR replaces this syntax with JSON based code arguments. JSON is used as it's a well-established future-proof standard. Other markdown processors like [R markdown](https://rmarkdown.rstudio.com/lesson-3.html) and [Markdown Preview Enhanced](https://shd101wyy.github.io/markdown-preview-enhanced/#/code-chunk) have a similar curly brace notation for arguments, but their entire notation is slightly different, using = instead of : for example. However, this PR uses JSON over such custom syntax, as non-standard syntax isn't as future-proof.

Specifying pre and post blocks now looks like

````
```python {"export": "pre"}
print('pre block')
```

```python {"export": "post"}
print('post block')
```
````
Possible values for the `export` argument are `pre` and `post`. The functionality of pre and post blocks remains unchanged.

This PR also makes it possible to specify other code block arguments, leaving possibilities for introducing features such as hiding code blocks. This PR introduces two other arguments, the first of which is the ability to ignore exports. For example,

````
```python {"export": "pre"}
print('pre block')
```

```python {"export": "post"}
print('post block')
```

```python {"ignoreExports": ["pre"]}
print('this will not run the `pre-block`, but it will run the `post-block`')
```

```python {"ignoreExports": ["post", "global"]}
print('this will not run the `post-block` or any global injects, but it will run the `pre-block`')
```

```python {"ignoreExports": "all"}
print('this will not run any pre or post blocks, or any global injects')
```
````
Possible values for the `ignoreExports` argument are an array of `pre`, `post`, `global`, *or* the string `all`.

Finally, this PR adds the ability for named exports. It does so by introducing the argument `label`: each code block can specify a label, which is simply a string to uniquely identify the code block on the document:

````
```python {"label": "labeledExport"}
print('labeled export')
```
````

These can then be imported in a code block using the `import` argument, which accepts an array of strings that correspond to labels of other code blocks on the same document:

````
```python {"label": "labeledExport"}
print('labeled export')
```

```python {"import": ["labeledExport"]}
print('this will run the labeled export')
```
````

The order in which labeled exports are specified in the `import` array will specify the order in which they will be included, where the first import in the array will be on top of the remaining imports. It is, however, impossible to import a code block defined below, remaining consistent with pre and post blocks.

Named exports will be placed below pre blocks, so this is how the hierarchy of code injects looks like now:

````
global injects
pre exports
named exports
<actual code block source>
post exports
````

The complete code block arguments interface looks like this:

```typescript
interface CodeBlockArgs {
	label?: string;
	import?: string[];
	export?: "pre" | "post";
	ignoreExports?: ("pre" | "post" | "global")[] | "all";
}
```

Since the arguments are separated from the language by a space / curly bracket, obsidian will ignore the arguments and will render the code block as normal, removing the need for custom code block renderers (apart from `run-` blocks, it would be good to see if this syntax can also be converted to the new code block arguments eventually).

This PR also reads the file contents directly from `this.app.workspace.getActiveViewOfType(MarkdownView).data` instead of unnecessarily loading the file again, resulting in a performance improvement. In addition, this PR refactors the code transform logic into a separate module to reduce the complexity of main.

### CODE REVIEW

**Comment by qiaogaojian** [comment]
I have a diffident opinion, I think the "pre- and post- "syntax is easy understood and elegant.

**Comment by twibiral** [comment]
Thanks for the effort, I really appreciate it. But I think this doesn't add much more functionality but makes it more complicated to use this feature. I prefer to keep your old implementation.

I think it's reasonable to keep this PR open. Maybe we change something in the future that makes this (or a similar implementation) necessary.

**Comment by twibiral** [comment]
I agree that it's better to add another syntax to keep compatibility with other markdown editors. But I think using JSON is creating a too complex syntax for this. We don't always need the key-value syntax and quotation marks. 

I propose the following alternative syntax: `{pre, post, label=abc, import=cde, import={abc, cde}, ignore=pre, ignore=[post, pre]`

This is much simpler to use and still can achieve the same.

The following regex can extract the configurations from curly brackets: `(?:post|pre|label\s*=\s*(?P<label>\w+)|import\s*=\s*(?P<import>\w+|\[\s*\w+(?:\s*,\s*\w+)*\s*\])|ignore\s*=\s*(?P<ignore>\w+|\[\s*\w+(?:\s*,\s*\w+)*\s*\]))` (see https://regex101.com/r/OIdGP2/1)

**Comment by milan338** [comment]
Could we modify this syntax slightly? I think there needs to be distinction between key names and values, so if we're not using using quotes around keys, I think they'd be needed around values ([markdown preview enchanced](https://shd101wyy.github.io/markdown-preview-enhanced/#/code-chunk) does this in their syntax for example, we could use single quotes instead of double quotes for readability). Other than that, I think we could implement this using https://github.com/json5/json5, just replacing `:` with `=` and manually extracting the pre / post identifier (I couldn't get your regex working in javascript. This should be faster and more maintainable than regex).

So your example would look like `{pre, post, label='abc', import='cde', import=['abc', 'cde'], ignore='pre', ignore=['post', 'pre']}`. Do you think this is ok?

**Comment by twibiral** [comment]
I agree, using json this way seems to be the better option. 

(Don't forget to update your working branch with the newest updates)

**Comment by milan338** [comment]
I've implemented the new syntax and merged with the dev branch, let me know if it works on your end.

**Comment by twibiral** [comment]
Unfortunately, it does not work if I use multiple arguments. E.g. `{pre, post}` and `{pre, import='abc'}` throw a JSON error (`Failed to parse code block args: SyntaxError: JSON5: Invalid character '}' at 1:20`)

**Comment by milan338** [comment]
I didn't know you wanted to be able to set pre and post blocks at the same time, this seems like a bit of a weird use case (you could set it as a post block and manually import it to run as a pre and post block if you really wanted), but I can add it if you'd like. Setting `{pre, import='abc'}` works fine on my end though, this is what I'm using and it works, both of them can be run without issue:

````
```python {label='abc'}
print('abc')
```

```python {pre, import='abc'}
print('should import abc')
```
````

Could you please send what you're running?

**Comment by twibiral** [comment]
For some reason, it only happens now if I use pre and post.

I think some people probably have a use case for using pre and post together. Is it possible to implement it?

It would be better if exceptions when parsing the json are caught and reported as error while parsing the arguments. Can you add this?

**Comment by milan338** [comment]
I've made it so you can declare a block as both pre and post, let me know if it works with you. I've also added the invalid line to the error message when the arguments are invalid, is this what you meant with reporting the error?

**Comment by twibiral** [comment]
It looks great, thank you! I will test it as soon as I have time but I think it will work.

While looking at your code I noticed that you are parsing for "pre," and "post,". Does this also work when there are no other arguments following after pre/post, i.e. if there is no comma after the argument?

**Comment by milan338** [comment]
You're right it wouldn't work. I've changed it to just make sure there isn't a trailing quote which would indicate it's being used as an arg value like in `ignore='pre'`, otherwise it treats it as a pre / post export. Should also now be able to specify implicit pre / post exports anywhere in the args, not just at the beginning.

**Comment by twibiral** [comment]
It works like a charm now! Thank you for updating this, I think it will be a fundamental part of the plugin. 

Do you mind changing the README.md to explain how the updated feature works? (Either in a new pull request or by adding more commits to this one)

**Pull request merged**
